name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          registry: https://ghcr.io
          username: ${{ secrets.PACKAGE_USERNAME }}
          password: ${{ secrets.PACKAGE_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/akatgelar/nestjs-postgres-testcase:latest -f .docker/Dockerfile .
          docker push ghcr.io/akatgelar/nestjs-postgres-testcase:latest

      - name: Copy docker-compose file to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: .docker/docker-compose.yml
          target: /home/app/nestjs-postgres-testcase/
          strip_components: 1

      - name: Deploy docker-compose on VPS
        uses: appleboy/ssh-action@master
        env:
          ENV: ${{ secrets.ENV }}
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          envs: ENV
          script: |
            cd /home/app/nestjs-postgres-testcase/
            echo "${{ secrets.PACKAGE_TOKEN }}" | docker login ghcr.io -username ${{ secrets.PACKAGE_USERNAME }} --password-stdin
            printf "$ENV" >> .env
            sudo docker compose stop
            sudo docker compose rm -f
            sudo docker compose pull
            sudo docker compose up -d 
